#!/bin/bash
python manage.py migrate
python manage.py collectstatic -c --noinput

nohup celery -A docker_wooey worker -c 4 --beat -l info >> celery.log 2>&1 &
gunicorn docker_wooey.wsgi:application --workers=2 -b 0.0.0.0:8080
